"""init

Revision ID: 53b695715c54
Revises: 
Create Date: 2025-11-18 18:38:09.582184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53b695715c54'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instalaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.String(length=80), nullable=True),
    sa.Column('aforo', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('admin', 'cliente', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('franjas_horarias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instalacion_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('capacidad', sa.Integer(), nullable=False),
    sa.Column('plazas_disponibles', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instalacion_id'], ['instalaciones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instalacion_id', 'fecha', 'hora_inicio', 'hora_fin', name='uq_slot')
    )
    op.create_index(op.f('ix_franjas_horarias_instalacion_id'), 'franjas_horarias', ['instalacion_id'], unique=False)
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('instalacion_id', sa.Integer(), nullable=False),
    sa.Column('franja_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('activa', 'cancelada', name='bookingstatus'), nullable=False),
    sa.ForeignKeyConstraint(['franja_id'], ['franjas_horarias.id'], ),
    sa.ForeignKeyConstraint(['instalacion_id'], ['instalaciones.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservas_franja_id'), 'reservas', ['franja_id'], unique=False)
    op.create_index(op.f('ix_reservas_instalacion_id'), 'reservas', ['instalacion_id'], unique=False)
    op.create_index(op.f('ix_reservas_usuario_id'), 'reservas', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservas_usuario_id'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_instalacion_id'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_franja_id'), table_name='reservas')
    op.drop_table('reservas')
    op.drop_index(op.f('ix_franjas_horarias_instalacion_id'), table_name='franjas_horarias')
    op.drop_table('franjas_horarias')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('instalaciones')
    # ### end Alembic commands ###
